baseURL = 'https://0xthijs.github.io/'
languageCode = 'en-us'
title = 'Thijs van der Aa'
theme = 'PaperMod'

[params]
    defaultTheme = 'dark'
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    description = "HR Strategist. Building AI tools to solve workforce problems."
    
    [params.profileMode]
        enabled = true
        title = "Thijs van der Aa"
        subtitle = "HR Strategist. Building AI tools to solve workforce problems."
        imageUrl = "images/home-banner.png"
        imageTitle = "Thijs"
        buttons = [
            { name = "Projects", url = "projects" },
            { name = "About Me", url = "about" },
            { name = "GitHub", url = "https://github.com/0xthijs" }
        ]

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/0xthijs"

    [[params.socialIcons]]
        name = "linkedin"
        url = "https://linkedin.com/in/thijsvanderaa"

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10
